version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: php
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: nginx
    ports:
      - 8080:80
    labels:
      traefik.enable: true
      traefik.http.routers.nuitinfo.entrypoints: https
      traefik.http.routers.nuitinfo.rule: Host(`domain.tld`)
      traefik.http.routers.nuitinfo.tls: true
      traefik.http.routers.nuitinfo.tls.certresolver: prod
      traefik.http.services.nuitinfo.loadbalancer.server.port: 80
  
  db:
    image: mysql
    volumes: 
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: db

volumes:
  database: