version: "3"

services:
  php:
    build: .
    volumes: 
      - ./app:/app
  
  nginx:
    image: nginx:alpine
    volumes: 
      - ./app:/app:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
  
  db:
    image: mysql
    volumes: 
      - ./.db:/var/lib/mysql
    ports:
      - 8082:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: db
  
  yarn:
    build:
      context: .
      dockerfile: encore.Dockerfile
    #command: watch
    volumes: 
      - ./app/webpack.config.js:/app/webpack.config.js:ro
      - ./app/assets:/app/assets
      - ./app/public:/app/public
  
  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: pepa-linha
